### ISSUE TITLE
Unexpected character '@'

### ISSUE THREAD

**Issue by tvvignesh** [umbopepato/rollup-plugin-postcss-lit#32]
Hi. I just tried this plugin to use postcss with lit but encountered this error where `@` charset symbols are not supported (or am I doing anything wrong?)

Error:

<img width="694" alt="Capture" src="https://user-images.githubusercontent.com/1165845/93929248-33aa8d80-fd39-11ea-8120-da9dd78d2d2b.PNG">

The relevant css

```css
@charset "UTF-8";
.mdc-touch-target-wrapper {
  display: inline;
}
```

CC: @umbopepato
